### ISSUE TITLE
Correct links to other task views

### ISSUE THREAD

**Issue by szipper** [ropensci/hydrometeorology#12]
From Achim: 

> Please use `<view>...</view>` to link to other CRAN task views. The
> non-CRAN "views" should be regular `<a href="...">...</a>` tags. I would
> strongly encourage not to call these "task views" to avoid confusion among
> readers.

**Comment by ilapros** [comment]
Done this in commit d1ac5a51d7f0b1129d39469abe71d5adbc1eae40 - hopefully implemented the <view> tag correctly. RopenSci TaskView changed to Listing
