### ISSUE TITLE
Remove dupicate entries 

### ISSUE THREAD

**Issue by boshek** [ropensci/hydrometeorology#6]
Looks like in particular the [**Modeling**](https://github.com/ropensci/hydrometeorology/blob/master/hydrometeo.md#modeling) section has some duplication.

**Comment by ilapros** [comment]
This is my fault - those were merging conflicts which I thought I had fixed - I'll get on to those. Sorry

**Comment by ilapros** [comment]
Hopefully fixed by [this](https://github.com/ropensci/hydrometeorology/commit/7f6613d7fd97e8c76ed5548d057e54d6eebfcfe6) commit

**Comment by szipper** [comment]
I actually put some packages in multiple categories on purpose if they seemed to have functionality (for example, data retrieval and spatial data processing). Are you two OK with that?

**Comment by boshek** [comment]
Definitely. I think this was in reference to another issues which I think @ilapros has resolved.
