### ISSUE TITLE
Refer to packages in CRAN and not github

### ISSUE THREAD

**Issue by ilapros** [ropensci/hydrometeorology#7]
For some packages the github tag is used, although they exist on CRAN. I imagine we should link the CRAN version of the package, which is supposedly not in development and which can be installed without devtools. 
Noticed for EGRET, EGRETci - others seem OK but worth double checking

**Comment by boshek** [comment]
Yes i agree completely. Presumably then users can navigate to the dev version via the CRAN page.

**Comment by boshek** [comment]
Fixed mostly via this [commit](3ca6fd58a5edf6340733b45633aba33f30054900)
