### ISSUE TITLE
Packages to add

### ISSUE THREAD

**Issue by szipper** [ropensci/hydrometeorology#8]
https://cran.r-project.org/web/packages/lfstat/index.html
https://cran.r-project.org/web/packages/Evapotranspiration/index.html

**Comment by szipper** [comment]
Compare with list by Rigon: https://abouthydrology.blogspot.com/2012/08/r-resources-for-hydrologists.html

**Comment by ilapros** [comment]
I started looking at some of those and have some concerns
https://github.com/tpilz/lumpR -- is it in line with the TV
https://github.com/jacobteter/CropWatR -- a bit too under-developed? 
https://cran.r-project.org/web/packages/RMAWGEN/ --  a weather generator. In line with TV?

**Comment by szipper** [comment]
@ilapros my gut reaction is that lumpR and RMAWGEN would be worth putting in - my general philosophy is to err on the side of including things - but I agree that CropWatR is looking like it is not ready yet (still on draft one and hasn't been updated in 3 years...)

**Comment by boshek** [comment]
I'm inclined to agree with @szipper. Ultimately users of the TV can raises issues here if they think it is problematic.

**Comment by szipper** [comment]
Completed in commit 77d54f1

**Comment by ilapros** [comment]
I posted the draft to a "Hydrology in R" Facebook group and received some further addition - I skimmed these add added the ones with a star which seemed general enough in 2e92902690a538982d2188a50c4728907bda022f 
1*. MODISTools: https://cran.r-project.org/.../MODISTools/MODISTools.pdf
2. quickmapr: https://cran.r-project.org/.../quickmapr/quickmapr.pdf
3*. MBC: https://cran.r-project.org/web/packages/MBC/MBC.pdf
4*. smapr: https://cran.r-project.org/web/packages/smapr/smapr.pdf
5*. musica: https://cran.r-project.org/web/packages/musica/musica.pdf
6. raster: https://cran.r-project.org/web/packages/raster/raster.pdf
7*. hydromad
8. rqgis:https://cran.r-project.org/web/packages/RQGIS/RQGIS.pdf
9*. MODIStsp: https://cran.r-project.org/.../pack.../MODIStsp/MODIStsp.pdf
10*. lulcc: https://cran.r-project.org/web/packages/lulcc/lulcc.pdf

**Comment by boshek** [comment]
I think this is a great list and your curation makes sense @ilapros. Those that you didn't include can be found in the spatial task view. So I think we can close this right?

**Comment by szipper** [comment]
Yeah I think so... I imagine there will always be more packages to add as people keep making more stuff, so maybe let's close this thread then a new Issue can be raised for future packages (or they can just be added directly as a commit without the intermediate step...)
