### ISSUE TITLE
additional text in hydrometeorology

### ISSUE THREAD

**Issue by boshek** [ropensci/hydrometeorology#9]
These tags are causing problems with the MakeFile for me: https://github.com/ropensci/hydrometeorology/blame/master/hydrometeo.md#L38

These seem like really good info. Perhaps we can incorporate them directly into each package description?

@ilapros Can I ask where you thought these would eventually be displayed?

**Comment by boshek** [comment]
That makes sense. I was having some issues with `ctv::ctv2html()` when including the comments so maybe we can just eliminate them entirely?

**Comment by szipper** [comment]
That sounds fine to me! We can always look at the revision log if we want
to revive the commented out portions...


--Sent from my phone, please ecxuse any typos--

**Comment by szipper** [comment]
Removed in commit 991308e
